package pbvalidator

import (
	"context"
	"encoding/json"
	"fmt"
)

// EmbeddedProvider returns a SchemaProvider that reads from the schema data
// embedded in the binary at compile time (generated by cmd/generate).
// No filesystem access is needed.
func EmbeddedProvider() SchemaProvider {
	return &embeddedProvider{}
}

type embeddedProvider struct{}

func (p *embeddedProvider) GetManifest(_ context.Context) (*Manifest, error) {
	var m Manifest
	if err := json.Unmarshal(embeddedManifestJSON, &m); err != nil {
		return nil, fmt.Errorf("parsing embedded manifest: %w", err)
	}
	return &m, nil
}

func (p *embeddedProvider) GetSchemaData(_ context.Context, path string) (json.RawMessage, error) {
	data, ok := embeddedSchemas[path]
	if !ok {
		return nil, fmt.Errorf("embedded schema not found: %s", path)
	}
	return json.RawMessage(data), nil
}
