// Command generate reads the repo-level schemas/ directory and produces:
//   - packages/go/schemas_gen.go — manifest + all schema JSON as Go constants
//   - packages/go/bidders/pbjs.go and pbs.go — typed Go structs for every bidder
//
// Run from the repo:
//
//	cd packages/go && go generate ./...
package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"unicode"
)

// manifest mirrors the top-level manifest.json structure.
type manifest struct {
	Version string                    `json:"version"`
	Sources map[string]json.RawMessage `json:"sources,omitempty"`
	Bidders map[string]bidderEntry    `json:"bidders"`
}

type bidderEntry struct {
	Pbjs *schemaRef `json:"pbjs"`
	Pbs  *schemaRef `json:"pbs"`
}

type schemaRef struct {
	Schema string `json:"schema"`
}

type jsonSchema struct {
	Type        interface{}            `json:"type"`
	Properties  map[string]jsonSchema  `json:"properties"`
	Required    []string               `json:"required"`
	Description string                 `json:"description"`
	Items       *jsonSchema            `json:"items"`
	Title       string                 `json:"title"`
	AnyOf       []jsonSchema           `json:"anyOf"`
	OneOf       []jsonSchema           `json:"oneOf"`
}

func main() {
	goPackageDir, err := findGoPackageDir()
	if err != nil {
		log.Fatalf("finding package dir: %v", err)
	}
	repoRoot := filepath.Join(goPackageDir, "..", "..")
	srcSchemas := filepath.Join(repoRoot, "schemas")

	log.Println("reading manifest...")
	mfData, err := os.ReadFile(filepath.Join(srcSchemas, "manifest.json"))
	if err != nil {
		log.Fatalf("reading manifest: %v", err)
	}
	var mf manifest
	if err := json.Unmarshal(mfData, &mf); err != nil {
		log.Fatalf("parsing manifest: %v", err)
	}

	log.Println("generating schemas_gen.go...")
	if err := generateSchemasGo(srcSchemas, goPackageDir, mf, mfData); err != nil {
		log.Fatalf("generating schemas_gen.go: %v", err)
	}

	biddersDir := filepath.Join(goPackageDir, "bidders")
	os.MkdirAll(biddersDir, 0o755)

	log.Println("generating pbjs structs...")
	if err := generateFile(srcSchemas, biddersDir, "pbjs", mf, func(be bidderEntry) *schemaRef { return be.Pbjs }); err != nil {
		log.Fatalf("generating pbjs: %v", err)
	}

	log.Println("generating pbs structs...")
	if err := generateFile(srcSchemas, biddersDir, "pbs", mf, func(be bidderEntry) *schemaRef { return be.Pbs }); err != nil {
		log.Fatalf("generating pbs: %v", err)
	}

	log.Println("done.")
}

func findGoPackageDir() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found")
		}
		dir = parent
	}
}

// generateSchemasGo produces schemas_gen.go containing the manifest and every
// referenced schema as Go byte-slice constants, eliminating the need to copy
// JSON files into the Go package.
func generateSchemasGo(srcSchemas, goPackageDir string, mf manifest, mfData []byte) error {
	type schemaFile struct {
		path string // relative path used in manifest (e.g. "pbjs/appnexus.json")
		data []byte
	}

	seen := make(map[string]bool)
	var files []schemaFile

	for _, be := range mf.Bidders {
		for _, ref := range []*schemaRef{be.Pbjs, be.Pbs} {
			if ref == nil || ref.Schema == "" || seen[ref.Schema] {
				continue
			}
			seen[ref.Schema] = true
			data, err := os.ReadFile(filepath.Join(srcSchemas, filepath.FromSlash(ref.Schema)))
			if err != nil {
				log.Printf("warning: skipping schema %s: %v", ref.Schema, err)
				continue
			}
			files = append(files, schemaFile{path: ref.Schema, data: data})
		}
	}

	sort.Slice(files, func(i, j int) bool { return files[i].path < files[j].path })

	var buf strings.Builder
	buf.WriteString("// Code generated by cmd/generate; DO NOT EDIT.\n\n")
	buf.WriteString("package pbvalidator\n\n")

	buf.WriteString("// embeddedManifestJSON is the raw manifest.json content.\n")
	buf.WriteString(fmt.Sprintf("var embeddedManifestJSON = []byte(%s)\n\n", quoteJSON(mfData)))

	buf.WriteString("// embeddedSchemas maps schema paths to their raw JSON content.\n")
	buf.WriteString("var embeddedSchemas = map[string][]byte{\n")
	for _, f := range files {
		buf.WriteString(fmt.Sprintf("\t%q: %s,\n", f.path, quoteJSON(f.data)))
	}
	buf.WriteString("}\n")

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		debugPath := filepath.Join(goPackageDir, "schemas_gen_debug.go")
		os.WriteFile(debugPath, []byte(buf.String()), 0o644)
		return fmt.Errorf("formatting schemas_gen.go (debug written to %s): %w", debugPath, err)
	}
	return os.WriteFile(filepath.Join(goPackageDir, "schemas_gen.go"), formatted, 0o644)
}

func generateFile(schemasRoot, biddersDir, runtime string, mf manifest, getRef func(bidderEntry) *schemaRef) error {
	type entry struct {
		code   string
		schema jsonSchema
	}
	var entries []entry

	for code, be := range mf.Bidders {
		ref := getRef(be)
		if ref == nil || ref.Schema == "" {
			continue
		}
		data, err := os.ReadFile(filepath.Join(schemasRoot, filepath.FromSlash(ref.Schema)))
		if err != nil {
			log.Printf("warning: skipping %s/%s: %v", runtime, code, err)
			continue
		}
		var s jsonSchema
		if err := json.Unmarshal(data, &s); err != nil {
			log.Printf("warning: skipping %s/%s: %v", runtime, code, err)
			continue
		}
		entries = append(entries, entry{code: code, schema: s})
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].code < entries[j].code
	})

	runtimePrefix := toPascalCase(runtime)

	var buf strings.Builder
	buf.WriteString("// Code generated by cmd/generate; DO NOT EDIT.\n\n")
	buf.WriteString("package bidders\n\n")

	for _, e := range entries {
		structName := runtimePrefix + bidderToGoName(e.code)
		writeStruct(&buf, structName, e.schema, e.code, runtime)
	}

	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		// Write unformatted for debugging
		debugPath := filepath.Join(biddersDir, runtime+"_debug.go")
		os.WriteFile(debugPath, []byte(buf.String()), 0o644)
		return fmt.Errorf("formatting %s.go (debug written to %s): %w", runtime, debugPath, err)
	}
	return os.WriteFile(filepath.Join(biddersDir, runtime+".go"), formatted, 0o644)
}

func writeStruct(buf *strings.Builder, structName string, s jsonSchema, bidderCode, runtime string) {
	if len(s.Properties) == 0 {
		return
	}

	requiredSet := make(map[string]bool, len(s.Required))
	for _, r := range s.Required {
		requiredSet[r] = true
	}

	desc := s.Description
	if desc == "" {
		desc = s.Title
	}
	if desc != "" {
		buf.WriteString(fmt.Sprintf("// %s represents params for the %q bidder (%s).\n", structName, bidderCode, runtime))
		buf.WriteString(fmt.Sprintf("// %s\n", sanitizeComment(desc)))
	} else {
		buf.WriteString(fmt.Sprintf("// %s represents params for the %q bidder (%s).\n", structName, bidderCode, runtime))
	}
	buf.WriteString(fmt.Sprintf("type %s struct {\n", structName))

	propNames := sortedKeys(s.Properties)
	fieldNames := deduplicateFieldNames(propNames)
	allNested := make(map[string]nestedDef)

	for i, propName := range propNames {
		prop := s.Properties[propName]
		fieldName := fieldNames[i]
		goType, nested := resolveGoType(prop, structName+fieldName, requiredSet[propName])

		for k, v := range nested {
			allNested[k] = v
		}

		tag := fmt.Sprintf("`json:\"%s,omitempty\"`", propName)
		if prop.Description != "" {
			buf.WriteString(fmt.Sprintf("\t// %s\n", sanitizeComment(prop.Description)))
		}
		buf.WriteString(fmt.Sprintf("\t%s %s %s\n", fieldName, goType, tag))
	}

	buf.WriteString("}\n\n")

	nestedNames := make([]string, 0, len(allNested))
	for name := range allNested {
		nestedNames = append(nestedNames, name)
	}
	sort.Strings(nestedNames)
	for _, name := range nestedNames {
		nd := allNested[name]
		writeNestedStruct(buf, name, nd)
	}
}

// deduplicateFieldNames assigns unique Go field names for a sorted list of
// JSON property names. When snake_case and camelCase variants collide (e.g.
// "inv_code" and "invCode" both -> "InvCode"), the second gets an "Alt" suffix.
func deduplicateFieldNames(propNames []string) []string {
	names := make([]string, len(propNames))
	seen := make(map[string]bool, len(propNames))
	for i, propName := range propNames {
		name := propToFieldName(propName)
		if seen[name] {
			name += "Alt"
			for seen[name] {
				name += "2"
			}
		}
		seen[name] = true
		names[i] = name
	}
	return names
}

type nestedDef struct {
	props    map[string]jsonSchema
	required []string
	desc     string
}

func writeNestedStruct(buf *strings.Builder, name string, nd nestedDef) {
	requiredSet := make(map[string]bool, len(nd.required))
	for _, r := range nd.required {
		requiredSet[r] = true
	}

	if nd.desc != "" {
		buf.WriteString(fmt.Sprintf("// %s holds nested parameters.\n// %s\n", name, sanitizeComment(nd.desc)))
	} else {
		buf.WriteString(fmt.Sprintf("// %s holds nested parameters.\n", name))
	}
	buf.WriteString(fmt.Sprintf("type %s struct {\n", name))

	propNames := sortedKeys(nd.props)
	fieldNames := deduplicateFieldNames(propNames)
	childNested := make(map[string]nestedDef)

	for i, propName := range propNames {
		prop := nd.props[propName]
		fieldName := fieldNames[i]
		goType, nested := resolveGoType(prop, name+fieldName, requiredSet[propName])

		for k, v := range nested {
			childNested[k] = v
		}

		tag := fmt.Sprintf("`json:\"%s,omitempty\"`", propName)
		if prop.Description != "" {
			buf.WriteString(fmt.Sprintf("\t// %s\n", sanitizeComment(prop.Description)))
		}
		buf.WriteString(fmt.Sprintf("\t%s %s %s\n", fieldName, goType, tag))
	}

	buf.WriteString("}\n\n")

	childNames := make([]string, 0, len(childNested))
	for n := range childNested {
		childNames = append(childNames, n)
	}
	sort.Strings(childNames)
	for _, n := range childNames {
		writeNestedStruct(buf, n, childNested[n])
	}
}

// resolveGoType maps a JSON Schema property to a Go type string.
// It returns a map of nested struct definitions (name -> def) that need to be emitted.
func resolveGoType(prop jsonSchema, nestedName string, required bool) (string, map[string]nestedDef) {
	types := schemaTypes(prop)

	if len(types) > 1 {
		return "any", nil
	}

	t := ""
	if len(types) == 1 {
		t = types[0]
	}

	if t == "" && (len(prop.AnyOf) > 0 || len(prop.OneOf) > 0) {
		return "any", nil
	}

	var goType string
	var nested map[string]nestedDef

	switch t {
	case "string":
		goType = ptrIf("string", !required)
	case "integer":
		goType = ptrIf("int64", !required)
	case "number":
		goType = ptrIf("float64", !required)
	case "boolean":
		goType = ptrIf("bool", !required)
	case "array":
		elemType := "any"
		if prop.Items != nil {
			elemType, nested = resolveGoType(*prop.Items, nestedName+"Item", false)
			elemType = strings.TrimPrefix(elemType, "*")
		}
		goType = "[]" + elemType
	case "object":
		if len(prop.Properties) > 0 {
			goType = "*" + nestedName
			nested = map[string]nestedDef{
				nestedName: {
					props:    prop.Properties,
					required: prop.Required,
					desc:     prop.Description,
				},
			}
		} else {
			goType = "map[string]any"
		}
	default:
		goType = "any"
	}

	return goType, nested
}

func schemaTypes(s jsonSchema) []string {
	if s.Type == nil {
		return nil
	}
	switch v := s.Type.(type) {
	case string:
		return []string{v}
	case []interface{}:
		var out []string
		for _, t := range v {
			if ts, ok := t.(string); ok {
				out = append(out, ts)
			}
		}
		return out
	}
	return nil
}

func ptrIf(typ string, ptr bool) string {
	if ptr {
		return "*" + typ
	}
	return typ
}

var (
	reUnderscore = regexp.MustCompile(`[_\-]+`)
	reLeadDigit  = regexp.MustCompile(`^\d`)
)

// bidderToGoName converts a bidder code like "appnexus", "33across", "ci_fixture"
// to a PascalCase Go identifier fragment.
func bidderToGoName(code string) string {
	parts := reUnderscore.Split(code, -1)
	var sb strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		sb.WriteString(capitalize(part))
	}
	name := sb.String()
	if reLeadDigit.MatchString(name) {
		name = "X" + name
	}
	return name
}

// propToFieldName converts a JSON property name to a PascalCase Go field name.
func propToFieldName(name string) string {
	parts := reUnderscore.Split(name, -1)
	var sb strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		sb.WriteString(capitalize(part))
	}
	result := sb.String()
	if result == "" {
		return "Field"
	}
	if reLeadDigit.MatchString(result) {
		result = "X" + result
	}
	// Handle Go reserved words
	switch strings.ToLower(result) {
	case "type", "range", "map", "func", "interface", "select", "case", "default", "package", "import", "var", "const", "return", "break", "continue", "go", "chan", "defer", "fallthrough", "goto", "struct", "switch":
		result = result + "Field"
	}
	return result
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	// Handle common acronyms
	upper := strings.ToUpper(s)
	switch upper {
	case "ID", "URL", "HTTP", "HTTPS", "API", "URI", "IP", "HTML", "CSS", "JS":
		return upper
	}
	runes := []rune(s)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func toPascalCase(s string) string {
	parts := reUnderscore.Split(s, -1)
	var sb strings.Builder
	for _, part := range parts {
		sb.WriteString(capitalize(part))
	}
	return sb.String()
}

func sortedKeys(m map[string]jsonSchema) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// quoteJSON returns a Go expression string representing a []byte literal for
// the given JSON data. Uses raw string literals when possible; falls back to
// fmt.Sprintf %q when the data contains backticks.
func quoteJSON(data []byte) string {
	s := string(data)
	if !strings.Contains(s, "`") {
		return "[]byte(`" + s + "`)"
	}
	return fmt.Sprintf("[]byte(%q)", s)
}

// sanitizeComment ensures a string is safe to use in a Go line comment.
func sanitizeComment(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "\r", "")
	if len(s) > 200 {
		s = s[:197] + "..."
	}
	return s
}
